language-servers:
  csharp:
    command: >
      dotnet $HOME/.csharp-lsp/Microsoft.CodeAnalysis.LanguageServer.dll
        --logLevel=Information
        --extensionLogDirectory=$HOME/.csharp-lsp/logs
        --stdio
    extensions:
      .cs: csharp
      .cshtml: razor
      .razor: razor
    workspace_loader: 'csharp'
    workspace_files:
      - '*.sln'
      - '*.csproj'
    diagnostics:
      strategy: 'pull'
