lsps:
  csharp:
    command: '/tmp/lsp/Microsoft.CodeAnalysis.LanguageServer --logLevel=Information --extensionLogDirectory=/tmp/lsp-logs --stdio'
    workspace_loader: 'csharp'
    extensions:
      '.cs': 'csharp'
    workspace_files:
      - '*.sln'
      - '*.csproj'
    diagnostics:
      strategy: 'pull'