lsps:
  go:
    command: gopls
    workspace_files:
      - 'go.mod'
      - 'go.work'
    diagnostics:
      strategy: 'push'
      wait_timeout_ms: 2000
    environment:
      GOPATH: '$HOME/go'
      GOCACHE: '$HOME/.cache/go-build'
      GOMODCACHE: '$HOME/go/pkg/mod'
