lsps:
  pyright:
    command: ${LOCAL_NODE_MODULE}/pyright:pyright-langserver --stdio
    workspace_files:
      - 'pyproject.toml'
      - 'requirements.txt'
      - 'setup.py'
      - 'Pipfile'
    diagnostics:
      strategy: 'pull'
