lsps:
  rust:
    command: 'rust-analyzer'
    extensions:
      '.rs': 'rust'
    workspace_files:
      - 'Cargo.toml'
      - 'Cargo.lock'
    diagnostics:
      strategy: 'push'
      wait_timeout_ms: 2000