lsps:
  typescript:
    command: ${LOCAL_NODE_MODULE}/typescript-language-server --stdio
    extensions:
      '.js': 'javascript'
      '.mjs': 'javascript'
      '.cjs': 'javascript'
      '.jsx': 'javascriptreact'
      '.ts': 'typescript'
      '.mts': 'typescript'
      '.cts': 'typescript'
      '.tsx': 'typescriptreact'
      '.json': 'json'
    workspace_files:
      - 'package.json'
      - 'tsconfig.json'
    # For the search functionality to work a file in the workspace needs to always kept open
    # As a workaround we specify one file that would be kept open on the Language Server side
    # Other files will be opened/closed as needed
    preload_files:
      - './src/index.ts'
    diagnostics:
      strategy: 'push'
      wait_timeout_ms: 2000
