lsps:
  typescript:
    command: typescript-language-server --stdio
    extensions:
      '.js': 'javascript'
      '.mjs': 'javascript'
      '.cjs': 'javascript'
      '.jsx': 'javascriptreact'
      '.ts': 'typescript'
      '.mts': 'typescript'
      '.cts': 'typescript'
      '.tsx': 'typescriptreact'
      '.json': 'json'
    workspace_files:
      - 'package.json'
      - 'tsconfig.json'
    preload_files:
      - './src/index.ts'
    diagnostics:
      strategy: 'push'
      wait_timeout_ms: 2000
